version: "3.7"


services:

  zookeeper:
    hostname: zookeeper
    image: wurstmeister/zookeeper
    expose:
      - "2181"
    ports:
      - "2181:2181"


  kafka:
    image: wurstmeister/kafka
    env_file:
      - kafka/kafka-variables.env
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'


  api:
    build:
      context: CompanyManager-api/.
    ports:
      - "8005:8005"
    env_file:
      - .env
    environment:
      - "KAFKA_BOOTSTRAP_SERVERS=kafka:9092"
    depends_on:
      - kafka

  company:
    build:
      context: CompanyManager-company/.
    ports:
      - "8006:8006"
    env_file:
      - .env
    environment:
      - "KAFKA_BOOTSTRAP_SERVERS=kafka:9092"
      - "BROADCAST=false"
    depends_on:
      - kafka
      - postgresdb


  employee:
    build:
      context: CompanyManager-employee/.
    ports:
      - "8007:8007"
    env_file:
      - .env
    environment:
      - "KAFKA_BOOTSTRAP_SERVERS=kafka:9092"
    depends_on:
      - kafka
      - postgresdb


  postgresdb:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - database-inf:/var/lib/postgresql/data/

volumes:
      database-inf:

