version: "3.7"


services:

  zookeeper:
    hostname: zookeeper
    image: wurstmeister/zookeeper
    expose:
      - "2181"
    ports:
      - "2181:2181"


  kafka:
    image: wurstmeister/kafka
    env_file:
      - env/kafka-variables.env
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'

  api:
    build:
      context: CompanyManager-api/.
    ports:
      - "8005:8005"
    env_file:
      - env/.env
    depends_on:
      - kafka

  company:
    build:
      context: CompanyManager-company/.
    ports:
      - "8006:8006"
    env_file:
      - env/.env
    environment:
      - "KAFKA_BROKERS=kafka:9092"
      - "BROADCAST=false"
    depends_on:
      - kafka
      - postgresdb


  employee:
    build:
      context: CompanyManager-employee/.
    ports:
      - "8007:8007"
    env_file:
      - env/.env
    environment:
      - "KAFKA_BROKERS=kafka:9092"
      - "BROADCAST=false"
    depends_on:
      - kafka
      - postgresdb

  tgbot:
    build:
      context: CompanyManager-tgbot/.
    ports:
      - "8008:8008"
    env_file:
      - env/tgbot-variables.env
    environment:
      - "KAFKA_BROKERS=kafka:9092"
      - "BROADCAST=false"
    links:
      - redis
    depends_on:
      - kafka


  postgresdb:
    image: postgres:latest
    env_file:
      - env/.env
    ports:
      - "5432:5432"
    volumes:
      - database-inf:/var/lib/postgresql/data/

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
      database-inf:

